name: CI/CD Pipeline

on:
  push:
    branches: [master, enhancement/**]
  pull_request:
    branches: [master, enhancement/**]

jobs:
  build-test-deploy:
    name: Build, Test & Deploy on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run unit tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=. --cov-report=xml

      # Docker build and push only for Python 3.10
      - name: Log in to Docker Hub
        if: success() && matrix.python-version == '3.10'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: success() && matrix.python-version == '3.10'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest .

      - name: Push Docker image to Docker Hub
        if: success() && matrix.python-version == '3.10'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-ml-app:latest
